spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: INFO
    myaimentor_api: DEBUG
    org.springframework.web: DEBUG

jwt:
  secret: ${JWT_SECRET:dev-secret-change-me-please-this-is-only-for-local}

routes:
  user-service: http://localhost:8081
  mentor-service: http://localhost:8082
  chat-service: http://localhost:8083
